apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ical-proxy

resources:
- namespace.yaml
- rbac.yaml
- deployment.yaml
- autoscaling.yaml
- network-policy.yaml

# Uncomment to apply common labels to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: production

# Uncomment to set image tag
# images:
# - name: ghcr.io/konairius/ical-proxy
#   newTag: v1.0.0

# Uncomment to add resource patches
# patchesStrategicMerge:
# - patches/production-patches.yaml

# Uncomment for different environments
# configMapGenerator:
# - name: ical-proxy-config
#   envs:
#   - config/production.env
